name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.5'

      - name: Generate temporary keys
        run: |
          echo "SESSION_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV
          echo "CSRF_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Tidy dependencies
        run: go mod tidy

      - name: Build
        run: go build -v .

      - name: Run tests
        run: go test -v ./...

